### ISSUE TITLE
连接数据库报错

### ISSUE THREAD

**Issue by niaiwomattt** [yezihack/go-mygen#1]
执行：
```shell
go-mygen -h localhost -P 3306 -u root -p 123456 -d default
```
报错：
```json
{"level":"ERROR","time":"2019-11-12T14:00:26.187+0800","file":"go-mygen@v0.0.0-20190819095210-5d1c4266476d/cmd.go:29","msg":"","service":"go-mygen","err":"interface conversion: interface {} is nil, not string","stack":"goroutine 1 [running]:\nruntime/debug.Stack(0xc000142f48, 0x145cd20, 0xc0000b95f0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/yezihack/go-mygen.Cmd.func1()\n\t/Users/panbing/mypro/golang/pkg/mod/github.com/yezihack/go-mygen@v0.0.0-20190819095210-5d1c4266476d/cmd.go:29 +0x57\npanic(0x145cd20, 0xc0000b95f0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/yezihack/go-mygen.(*ModelS).findDbTables(0xc0000b0a20, 0x188b1f8, 0x0, 0x0, 0x0, 0x0)\n\t/Users/panbing/mypro/golang/pkg/mod/github.com/yezihack/go-mygen@v0.0.0-20190819095210-5d1c4266476d/services.go:39 +0x4f0\ngithub.com/yezihack/go-mygen.(*ModelS).GetTableNameAndComment(0xc0000b0a20, 0x2c, 0x15)\n\t/Users/panbing/mypro/golang/pkg/mod/github.com/yezihack/go-mygen@v0.0.0-20190819095210-5d1c4266476d/services.go:12 +0x8a\ngithub.com/yezihack/go-mygen.Commands(0x7ffeefbff814, 0xd, 0xcea, 0x7ffeefbff841, 0x3, 0x7ffeefbff848, 0x3, 0x7ffeefbff82d, 0x10, 0x14d7800, ...)\n\t/Users/panbing/mypro/golang/pkg/mod/github.com/yezihack/go-mygen@v0.0.0-20190819095210-5d1c4266476d/cmd.go:137 +0x287\ngithub.com/yezihack/go-mygen.Cmd.func2(0xc000178000, 0x0, 0xc000172070)\n\t/Users/panbing/mypro/golang/pkg/mod/github.com/yezihack/go-mygen@v0.0.0-20190819095210-5d1c4266476d/cmd.go:105 +0x322\ngithub.com/urfave/cli.HandleAction(0x143e260, 0xc00016c000, 0xc000178000, 0xc000178000, 0x0)\n\t/Users/panbing/mypro/golang/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:523 +0xbe\ngithub.com/urfave/cli.(*App).Run(0xc000166000, 0xc0000c4000, 0xb, 0xb, 0x0, 0x0)\n\t/Users/panbing/mypro/golang/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:285 +0x5df\ngithub.com/yezihack/go-mygen.Cmd()\n\t/Users/panbing/mypro/golang/pkg/mod/github.com/yezihack/go-mygen@v0.0.0-20190819095210-5d1c4266476d/cmd.go:113 +0x7dd\nmain.main()\n\t/Users/panbing/mypro/golang/pkg/mod/github.com/yezihack/go-mygen@v0.0.0-20190819095210-5d1c4266476d/go-mygen/main.go:7 +0x20\n"}
```

**Comment by yezihack** [comment]
你是win系统吗?

**Comment by niaiwomattt** [comment]
> 你是win系统吗?

我是Mac

**Comment by niaiwomattt** [comment]
大哥求救啊！

**Comment by niaiwomattt** [comment]
我好着急

**Comment by yezihack** [comment]
你直接git clone git@github.com:yezihack/go-mygen.git
cd $GOPATH/src/github.com/yezihack/go-mygen 
修改Makefile的29行的端口与-d的数据库名称 
再运行make dev

**Comment by yezihack** [comment]
> 我好着急

go install github.com/yezihack/go-mygen 
今天重构了一版本.你可以试试.
linux,win版本直接可以下载
https://github.com/yezihack/go-mygen/releases/tag/3.0.0beta

**Comment by yezihack** [comment]
> > 你是win系统吗?
> 
> 我是Mac
go install github.com/yezihack/go-mygen

**Comment by niaiwomattt** [comment]
谢谢，我再试试

**Comment by niaiwomattt** [comment]
对了我是 MySQL 8
