### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by SPP9014** [yezihack/go-mygen#4]
# Mac操作系统，执行
     ./go-mygen -h localhost -P 3306 -u root -p "Macabc;123" -d dbName
# 返回结果
```bash
2019/12/06 12:42:00 core.go:113: 数据库连接成功
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.(*ModelS).findDbTables(0xc0001102a0, 0x16aad40, 0x0, 0x0, 0x0, 0x0)
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/service.go:39 +0x4f0
main.(*ModelS).GetTableNameAndComment(0xc0001102a0, 0xc00001c2c0, 0x20)
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/service.go:12 +0x8a
main.Commands(0x13cef93, 0x1)
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/core.go:123 +0x2c5
main.start.func1(0xc0000d4160, 0x101010101, 0xc0000d4160)
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/core.go:48 +0x252
github.com/urfave/cli.HandleAction(0x135cf40, 0x13e8530, 0xc0000d4160, 0xc0000ba1e0, 0x0)
	/Users/sgfoot/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.(*App).Run(0xc0000a71e0, 0xc0000c0000, 0xb, 0xb, 0x0, 0x0)
	/Users/sgfoot/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x58c
main.start()
	/Users/sgfoot/go/src/github.com/yezihack/go-mygen/core.go:55 +0xa5
main.main()
```

**Comment by yezihack** [comment]
你是使用mac 3.0.0beta版本吗?

**Comment by yezihack** [comment]
https://github.com/yezihack/go-mygen/releases/download/3.0.0beta/go-mygen-3.0.0beta-darwin_amd64_.tar.gz 试一下这个
